name: test.yml

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  ga-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: devcontainers/ci@v0.3
      with:
        runCmd: npm run lint
